[programs.localnet]
protocol_event = "Q4JNMDYYGb1kktLz1yr6p5PktLvCyVCDcThzmjzji5i"

[programs.devnet]
protocol_event = "Q4JNMDYYGb1kktLz1yr6p5PktLvCyVCDcThzmjzji5i"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn runJestTests"
